---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 192.168.0.5
      ansible_user: kirill
      ansible_ssh_private_key_file: ~/.ssh/key2
vector:
  hosts:
    vector-01:
      ansible_host: 192.168.0.5
      ansible_user: kirill
      ansible_ssh_private_key_file: ~/.ssh/key2
